#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-json
Version  : 1.0.4
Release  : 3
URL      : https://github.com/javaee/jsonp/archive/jsonp-1.0.4.tar.gz
Source0  : https://github.com/javaee/jsonp/archive/jsonp-1.0.4.tar.gz
Source1  : https://repo1.maven.org/maven2/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar
Source2  : https://repo1.maven.org/maven2/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.pom
Source3  : https://repo1.maven.org/maven2/org/glassfish/json/1.0.4/json-1.0.4.pom
Source4  : https://repo1.maven.org/maven2/org/json/json/20090211/json-20090211.jar
Source5  : https://repo1.maven.org/maven2/org/json/json/20090211/json-20090211.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.1 GPL-2.0
Requires: mvn-json-data = %{version}-%{release}

%description
* javax.json-1.0.jar contains both "JSR 353 : Java API for JSON Processing" API and its default provider implementation. Keep it in classpath for both compiling and running your application.

%package data
Summary: data components for the mvn-json package.
Group: Data

%description data
data components for the mvn-json package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/javax.json/1.0.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/javax.json/1.0.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/json/1.0.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/json/1.0.4/json-1.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json/json/20090211
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/json/json/20090211/json-20090211.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/json/json/20090211
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/json/json/20090211/json-20090211.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar
/usr/share/java/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.pom
/usr/share/java/.m2/repository/org/glassfish/json/1.0.4/json-1.0.4.pom
/usr/share/java/.m2/repository/org/json/json/20090211/json-20090211.jar
/usr/share/java/.m2/repository/org/json/json/20090211/json-20090211.pom
